version: 18.1
services:
  worker:
    build: .
    environment:
      # Dont use ('') or (" ") for fill above sections >
      # This is not V2 full release üòÖ so some features are not still available
      SESSION: $SESSION
      DATABASE_URL: $DATABASE_URL
      BOT_NAME: HIL3M Bot olarak isimlendiriniz. üòø
      WORK_TYPE: private
      LANGUAGE: TR
      HANDLERS: ^[.?/#+-]
      USER_NAME: Free_User
      COMMAND_LIST_KEY: hilem
      ALIVE_MSG_KEY: alive
      SUDO: 905443787048
      SEND_REACT: true
      BLOCK_CHAT: false
      BLOCK_USERS: false
      SEND_READ: true
      PM_BLOCK: false
      NO_ONLINE: false
      NO_LOG: false
      BGM: off
      AI_LILY: false
      ANTI_LINK: false
      CUSTOM_BLOCK_LINKS: false
      AUTO_BIO: false
      BADWORDS_KICK: false
      ALIVE_MSG: default
      AFK_MSG: default
      KICKME_MSG: default
      ADD_MSG: default
      BAN_MSG: default
      PROMOTE_MSG: default
      DEMOTE_MSG: default
      MUTE_MSG: default
      UNMUTE_MSG: default
      BLOCK_MSG: default
      UNBLOCK_MSG: default
      CAPTION: Ôπù‚öïÔ∏èÔπû ·¥ç·¥Ä·¥Ö·¥á  ô è HIL3M Ôπù‚öïÔ∏èÔπû
      BIO_NAME: ·üö OTO BIO SISTEM ü§πüèª‚Äç‚ôÇÔ∏è
      COMMAND_EMOJI: Ôπù‚öóÔ∏èÔπû
      DESC_EMOJI: Ôπùü™™Ôπû
      WARN_EMOJI: Ôπù‚ö†Ô∏èÔπû
      ALIVE_PIC: https://telegra.ph/file/dc8e4edc7230cedbdec2c.jpg
      WLCM_GIF: https://telegra.ph/file/338cb7f0b2b01e463efcd.mp4
      GBYE_GIF: https://telegra.ph/file/88f85fe6850015ae49067.mp4
      DEBUG: debug
      OKTETO: false
